packages: []
lockfile: false
onlyBuiltDependencies:
  - "@karinjs/node-pty"
  - "@karinjs/sqlite3-cjs"
  - canvas
  - classic-level
  - protobufjs
  - puppeteer
  - sharp
  - sqlite3
patchedDependencies:
  douyin.ts@0.2.1: patches/douyin.ts@0.2.1.patch
publicHoistPattern:
  - "*sqlite3*"
  - "*express*"
